### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by mamigot** [mafshar/lost-n-found-service#1]
Please outline the dates and descriptions of the upcoming milestones of this project.

Would really help the community be "in sync" about any and all issues.

Gotta say that it feels like some members of the community have gone rogue lately.

It has created somewhat of a hostile work environment.

Neither my confidants nor I are prepared to give up, however.

Find a solution ASAP.

Mark our words: we will _fork_ this repository if we need to.

**Comment by radhikamattoo** [comment]
@mamigot get fukt

**Comment by mamigot** [comment]
🥸
